### ISSUE TITLE
[FE] When you click on the link in the email to remember your password, the website does not appear

### ISSUE THREAD

**Issue by ITAcademyAdmin** [IT-Academy-BCN/ita-landing-frontend#134]

**Comment by ITAcademyAdmin** [comment]
La web tiene que detectar la ruta, si es la de recordar contraseña (reset-password), abrir el popup de nueva contraseña.



![Image](https://github.com/IT-Academy-BCN/ita-landing-frontend/assets/92028251/2a8682e9-40cf-4623-858e-2931efcc9785)



Se necesitan 3 valores para llamar al endpoint de modificar contraseña:

- Token: se obtiene de la ruta
- Email: lo introduce el user
- Nueva contraseña: la introduce el user

Nota: Mirar swagger

**Comment by treee97** [comment]
Es posible que esto sea algo de backend?

https://github.com/IT-Academy-BCN/ita-landing-backend/blob/develop/resources/views/mail/forgetPassword.blade.php#L260

En este archivo de ita-landing-backend en la línea 260 está el link que nos lleva a cambiar contraseña pero en el `href` pone esto:

`http://localhost:3000/reset-password/{{$token}}`

Creo que no tengo manera de cambiar esa ruta ya que viene de backend verdad? 

El componente también funciona correctamente. He podido cambiar mi contraseña sin problemas.

**Comment by vicenlu** [comment]
Creo que la ruta nos puede valer en el front.

En el componente principal, hay que implementar un useEffect, que ejecute una función de checkear la ulr al inicio de la aplicación.

Este checkeo de la aplicación, debe leer la url usando el hook `useLocation()`;

Una vez tienes el path de la web, si es `reset-password`, se debe abrir el popup de nueva contraeña, usando un state para tal efecto.

El usuario introduce el email y la nueva contraseña. Con este email, contraseña y el token obtenido con useLocation, se llama a la API para cambiar la contraseña (validar que datos necesita el backend para cambiar la contraseña en swagger, creo que son esos tres).

**Comment by vicenlu** [comment]
Más info: https://www.codingbeautydev.com/blog/react-router-get-current-route
